//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpyGame.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpyGame.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔ APPLY.
        /// </summary>
        internal static string btnApplyText {
            get {
                return ResourceManager.GetString("btnApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Player Names.
        /// </summary>
        internal static string btnClearPlayerNamesText {
            get {
                return ResourceManager.GetString("btnClearPlayerNamesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btnConfirmText {
            get {
                return ResourceManager.GetString("btnConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 DONE.
        /// </summary>
        internal static string btnDoneText {
            get {
                return ResourceManager.GetString("btnDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW GAME.
        /// </summary>
        internal static string btnNewGameText {
            get {
                return ResourceManager.GetString("btnNewGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        internal static string btnPlayText {
            get {
                return ResourceManager.GetString("btnPlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Select Language.
        /// </summary>
        internal static string btnSelectLanguageText {
            get {
                return ResourceManager.GetString("btnSelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW SPIES.
        /// </summary>
        internal static string btnShowSpiesText {
            get {
                return ResourceManager.GetString("btnShowSpiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        internal static string lblAnimalsText {
            get {
                return ResourceManager.GetString("lblAnimalsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string lblCountriesText {
            get {
                return ResourceManager.GetString("lblCountriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER!.
        /// </summary>
        internal static string lblGameOverText {
            get {
                return ResourceManager.GetString("lblGameOverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings.
        /// </summary>
        internal static string lblGameSettingsText {
            get {
                return ResourceManager.GetString("lblGameSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string lblObjectsText {
            get {
                return ResourceManager.GetString("lblObjectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Spies.
        /// </summary>
        internal static string lblOtherSpiesText {
            get {
                return ResourceManager.GetString("lblOtherSpiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Spy Game, the board game you can enjoy anywhere, anytime. All you need is a group of friends and the right mood to dive in. To begin, you’ll first choose a theme. Each theme comes with its own set of words and a unique design, giving your game a fresh atmosphere and making every round feel exciting and different.E.
        /// </summary>
        internal static string lblPage1Paragrapgh1Text {
            get {
                return ResourceManager.GetString("lblPage1Paragrapgh1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Spy Game, there are two roles: AGENT and SPY. The Agents’ mission is to uncover who the Spy is, while the Spy’s goal is to avoid being discovered and escape elimination. It’s a battle of deduction, bluffing, and quick thinking, where every round brings new tension and fun..
        /// </summary>
        internal static string lblPage1Paragrapgh2Text {
            get {
                return ResourceManager.GetString("lblPage1Paragrapgh2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game starts, all Agents receive the same secret word. After reading it, they must memorize and keep it hidden. The Spy, however, gets no word at all. Their challenge is to act as if they know the word, blending in with the Agents without giving away their lack of knowledge..
        /// </summary>
        internal static string lblPage1Paragrapgh3Text {
            get {
                return ResourceManager.GetString("lblPage1Paragrapgh3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once everyone knows their role, the interrogation phase begins. Players first decide on how long this round will last—either by setting a time limit or agreeing on a fixed number of questions. Then, one by one, they ask and answer questions that hint at the secret word. The Agents should pay close attention, looking for slips or odd answers that might expose the Spy hiding among them..
        /// </summary>
        internal static string lblPage2Paragrapgh1Text {
            get {
                return ResourceManager.GetString("lblPage2Paragrapgh1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the questioning is over, it’s time to vote. Each player chooses the person they suspect is the Spy. If the group accuses an Agent by mistake, that Agent is eliminated and the game moves to the next round. But if the Spy is successfully identified, the Agents win the game instantly. The Spy’s only path to victory is surviving every vote without being caught..
        /// </summary>
        internal static string lblPage2Paragrapgh2Text {
            get {
                return ResourceManager.GetString("lblPage2Paragrapgh2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        internal static string lblPlacesText {
            get {
                return ResourceManager.GetString("lblPlacesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Names.
        /// </summary>
        internal static string lblPlayerNamesText {
            get {
                return ResourceManager.GetString("lblPlayerNamesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string lblPlayersText {
            get {
                return ResourceManager.GetString("lblPlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string lblSectionsText {
            get {
                return ResourceManager.GetString("lblSectionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Game Language.
        /// </summary>
        internal static string lblSelectGameLanguageText {
            get {
                return ResourceManager.GetString("lblSelectGameLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Other Spies Mode.
        /// </summary>
        internal static string lblShowOtherSpiesModeText {
            get {
                return ResourceManager.GetString("lblShowOtherSpiesModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spies.
        /// </summary>
        internal static string lblSpiesText {
            get {
                return ResourceManager.GetString("lblSpiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string lblSportsText {
            get {
                return ResourceManager.GetString("lblSportsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Word Was.
        /// </summary>
        internal static string lblTheWordWasText {
            get {
                return ResourceManager.GetString("lblTheWordWasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Left.
        /// </summary>
        internal static string lblTimeLeftText {
            get {
                return ResourceManager.GetString("lblTimeLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string lblTimeText {
            get {
                return ResourceManager.GetString("lblTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string lblTransportText {
            get {
                return ResourceManager.GetString("lblTransportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string PlayerLabel {
            get {
                return ResourceManager.GetString("PlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy Game.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
